### PR TITLE
[Android] support.

### PR DESCRIPTION
**Pull request by Guang1234567**
Hello dev:

Just support Android platform, thanks.

### CODE REVIEW

**Comment by mbarnach** [comment]
Hi @Guang1234567 
Thanks for the contribution! Very intriguing! Could you update the README.
Could you also describe (ideally in the README itself) how to compile/test such version. Are you relying on Scade? or Any other way?
Thanks.

**Comment by Guang1234567** [comment]
> Hi @Guang1234567
> Thanks for the contribution! Very intriguing! Could you update the README.
> Could you also describe (ideally in the README itself) how to compile/test such version. Are you relying on Scade? or Any other way?
> Thanks.

ok, wait a sec,  because update REAME.md need to publish Swift-Android-Toolchain-5.4.2 first.

Thanks.

**Comment by mbarnach** [comment]
Hi @Guang1234567 May I ask you why you've closed that PR?

**Comment by Guang1234567** [comment]
Have a trouble,  maybe re-pull-request late.

I don't have Linux OS,  so i cant test it under macOS, android, linux at the same time.

Only have macOS, android.

**Pull request closed without merging**
