### PR TITLE
Fix for the `Invalid Exclude` warnings in Xcode 13

### LINKED ISSUE #26: Invalid exclude warnings in Xcode 13
Xcode 13 shows some "Invalid exclude" warnings for these files:

- BlueSignals/Sources/Signals/Sources/Signals.h
- BlueSignals/Sources/Signals/Sources/Info.plist
- BlueSignals/Sources/Signals/Signal.xcodeproj
- BlueSignals/Sources/Signals/README.md
- BlueSignals/Sources/Signals/Tests

### PR DESCRIPTION
**Pull request by SMartorelli**
Fix for the `Invalid Exclude` warnings in Xcode 13

## Description
I removed the invalid exclusions and updated the .gitignore file as seen on other IBM-Swift projects after the update to Xcode 13.

## How Has This Been Tested?
Tested on my project using the forked repo. Warnings resolved and package working as expected.

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

I'm part of IBM org so I don't know if I need to submit a CLA form.
Close #26

### CODE REVIEW

**Review by mbarnach — APPROVED** [review]
Thanks for that!
👍

**Comment by SMartorelli** [comment]
Hi @mbarnach, do you have any plan for the merge of this PR?

**Comment by mbarnach** [comment]
@SMartorelli Yes indeed!
@dannys42 any objections?

**Comment by SMartorelli** [comment]
@mbarnach @dannys42 Just a reminder :)

**Comment by dannys42** [comment]
@SMartorelli Thanks for the ping and sorry for the delay!

**Comment by dannys42** [comment]
@SMartorelli Tagged and released.  Please let me know if this works for you.

**Pull request merged**
