### PR TITLE
chore: add Swift 4.2 to CI

### PR DESCRIPTION
**Pull request by ianpartridge**
Update this project so the CI runs on Swift 4.2, and tests Ubuntu 16.04 and 18.04 via Docker.

### CODE REVIEW

**Review by billabt — APPROVED** [review]
Changes look good to me.

**Comment by ianpartridge** [comment]
Not quite, if you look at the CI logs the new 16.04 and 18.04 Docker builds didn't work properly...

**Comment by billabt** [comment]
I looked at the logs, they look fine to me...  Here's what I looked at --> https://travis-ci.org/IBM-Swift/BlueSignals/builds/447754434

Then after the merge, here's the result of that build --> https://travis-ci.org/IBM-Swift/BlueSignals

Everything appears to be clean...  Did I miss something?

**Comment by ianpartridge** [comment]
The 18.04 build at https://travis-ci.org/IBM-Swift/BlueSignals/jobs/447754439 says that it used the 14.04 binaries:

```
>> Installing 'swift-4.2-RELEASE'...
--2018-10-29 12:05:10--  https://swift.org/builds/swift-4.2-release/ubuntu1404/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu14.04.tar.gz
```

**Comment by billabt** [comment]
Ahh, ok. I didn’t see that. 🤪

**Pull request merged**
